### PR TITLE
update build instructions and git ignore file for python virtual environment .venv

### PR DESCRIPTION
**Pull request by jakeheke75**

### CODE REVIEW

**Review by Twon — APPROVED** [review]
Thanks for the contribution. Please merge when ready!

**Comment by jakeheke75** [comment]
> Thanks for the contribution. Please merge when ready!

Thanks! I can't see any merge option at the bottom of the PR screen... Am I missing something? :thinking:

**Comment by Twon** [comment]
> > Thanks for the contribution. Please merge when ready!
> 
> Thanks! I can't see any merge option at the bottom of the PR screen... Am I missing something? :thinking: 

Ah right, I suspect I need to give you contributor rights in order for you to be able to commit. I will address this tonight.

**Comment by Twon** [comment]
> > > Thanks for the contribution. Please merge when ready!
> > 
> > 
> > Thanks! I can't see any merge option at the bottom of the PR screen... Am I missing something? 🤔
> 
> Ah right, I suspect I need to give you contributor rights in order for you to be able to commit. I will address this tonight.

I've added you as a contributor so check your email for the invite. Once accepted you should be able to merge changes once reviewed and the checks are passing.

**Pull request merged**
